"""Generate MT5 .set files for GoldRangeBreakout.mq5 from its input declarations.

Keeps the set files in sync with the EA: every `input` line is parsed for its
name and default, then per-set overrides and optimisation ranges are applied.

    python ea/make_sets.py
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "GoldRangeBreakout.mq5"
OUT = HERE / "sets"

# MQL5 constant values as stored in .set files
CONSTS = {
    "true": "true", "false": "false",
    "PERIOD_M1": 1, "PERIOD_M5": 5, "PERIOD_M15": 15, "PERIOD_M30": 30,
    "PERIOD_H1": 16385, "PERIOD_H4": 16388, "PERIOD_D1": 16408,
    "clrGold": 55295, "clrLimeGreen": 3329330, "clrTomato": 4678655, "clrSilver": 12632256,
}


def parse_inputs():
    enums = {}
    for body in re.findall(r"enum\s+\w+\s*\{(.*?)\};", SRC.read_text(), re.S):
        for name, val in re.findall(r"(\w+)\s*=\s*(-?\d+)", body):
            enums[name] = val
    inputs = []
    for line in SRC.read_text().splitlines():
        m = re.match(r"\s*input\s+(\w+)\s+(\w+)\s*=\s*([^;]+);", line)
        if not m:
            continue
        _, name, default = m.groups()
        default = default.strip().strip('"')
        default = str(enums.get(default, CONSTS.get(default, default)))
        inputs.append((name, default))
    return inputs


def write_set(filename, overrides=None, ranges=None):
    """ranges: {name: (start, step, stop)} -> marked for optimisation."""
    overrides, ranges = overrides or {}, ranges or {}
    inputs = parse_inputs()
    names = {n for n, _ in inputs}
    unknown = (set(overrides) | set(ranges)) - names
    assert not unknown, f"unknown inputs: {unknown}"
    lines = [f"; {filename} - generated by ea/make_sets.py"]
    for name, default in inputs:
        value = str(overrides.get(name, default))
        if name in ranges:
            start, step, stop = ranges[name]
            lines.append(f"{name}={value}||{start}||{step}||{stop}||Y")
        elif value in ("true", "false") or not re.fullmatch(r"-?[\d.]+", value):
            lines.append(f"{name}={value}")
        else:
            lines.append(f"{name}={value}||{value}||0||{value}||N")
    OUT.mkdir(exist_ok=True)
    (OUT / filename).write_text("\r\n".join(lines) + "\r\n", encoding="utf-8")
    print("wrote", OUT / filename)


if __name__ == "__main__":
    # 1) defaults: NY 09:30 range, pending stops, SL opposite side, TP 2R, fixed 0.1 lot
    write_set("GRB_XAUUSD_NY0930_default.set")

    # 2) same strategy, live-style sizing: 1% risk per trade from the real SL distance
    write_set("GRB_XAUUSD_NY0930_risk1pct.set", {"InpLotMode": 1, "InpRiskPercent": 1.0, "InpMagic": 26092702})

    # 3) stage-1 optimisation (entry side only, exits fixed) - run with "Custom max"
    write_set(
        "GRB_XAUUSD_opt_stage1_entry.set",
        {"InpShowPanel": "false", "InpDrawBoxes": "false"},
        {
            "InpCheckHour": (8, 1, 10),
            "InpRangeCandles": (6, 2, 32),
            "InpMaxRangeATR": (0.8, 0.1, 3.0),
            "InpBuyBufferPips": (0, 5, 30),
            "InpSellBufferPips": (0, 5, 30),
            "InpEntryWindowMin": (60, 30, 360),
            "InpEntryMode": (0, 1, 1),
        },
    )

    # 4) stage-2 optimisation (exits), load after locking the stage-1 winner
    write_set(
        "GRB_XAUUSD_opt_stage2_exit.set",
        {"InpShowPanel": "false", "InpDrawBoxes": "false"},
        {
            "InpSLMode": (0, 1, 2),
            "InpSLBeyondPips": (0, 10, 60),
            "InpSLPips": (50, 25, 300),
            "InpTPRR": (1.0, 0.25, 4.0),
            "InpCloseHour": (12, 1, 16),
            "InpBEStart": (0, 0.25, 2.0),
        },
    )
